# .streamlit/secrets.toml

# Gemini API Key (Enclosed in quotes)
GOOGLE_API_KEY = "AIzaSyDpjbjud9SxNK3UzAg6IX4AF6UDTdinpUA"

[postgres]
host = "aws-1-ap-southeast-1.pooler.supabase.com" 
database = "postgres"
user = "postgres.yofdpfdlsrkhanyxhdff" 
password = "hytex@123hytx"
port = 6543
sslmode = "require" 
# Supabase Public API Key (for pgvector access)
[supabase]
url = "https://yofdpfdlsrkhanyxhdff.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvZmRwZmRsc3JraGFueXhoZGZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MTk2NTUsImV4cCI6MjA3NTM5NTY1NX0.fMJMOz1WL2uH7gtRUQYlRvm8LCuULP5DRkwKYir-8q0"